<?php
/**
 * @file
 * Drupal hooks
 */

/**
 * Implements hook_search_api_alter_callback_info().
 */
function search_api_attachments_user_content_search_api_alter_callback_info() {
  $callbacks['search_api_attachments_user_content_alter_settings'] = array(
    'name' => t('File attachments in user content'),
    'description' => t('Extract the content of files attached to node content created by the user and index it.'),
    'class' => 'SearchApiAttachmentsUserContentAlterSettings',
  );
  return $callbacks;
}
